### ISSUE TITLE
 I cannot run the parampool examples :(

### ISSUE THREAD

**Issue by Trifonoff** [hplgit/parampool#1]
Dear Hans Petter Langtangen,

I am extremely interested in parampool! I am trying to make a Keplerian fitting program for radial velocity data and it seems that your work is exactly what I need.

(I tried web4sciapps-master - works fine, except that I cannot make the login page for some reason)

However, at the moment I feel like an idiot. I am reading the manual and still I cannot run even the parampool examples. I don’t know if the problem is in me or something is wrong with the code.

(I am using ubuntu 15.04)

For example if I try to generate flask1:
###### 

tito@terminator:~/web_plot/parampool-master/parampool/tests$ python generate_flask1.py 

**\* Warning:
mysimplefunc has positional arguments.
We recommend to use keyword arguments only since this
generator can then detect the type of each argument and
assign the proper form field type.
The default form field for the positional arguments is
FloatField, which requires explicit conversion
for all arguments that are not of this type.
See controller.py, # Convert data ... for what type
of code that may be needed.
Flask main application written to controller.py.
Usage: python controller.py
###### 

 then running  controller.py:
###### 

tito@terminator:~/web_plot/parampool-master/parampool/tests$ python controller.py 

Traceback (most recent call last):
  File "controller.py", line 5, in <module>
    from model import Mysimplefunc
  File "/home/tito/web_plot/parampool-master/parampool/tests/model.py", line 2, in <module>
    from parampool.html5.flask.fields import HTML5FloatField
  File "/usr/local/lib/python2.7/dist-packages/parampool/html5/flask/fields.py", line 10, in <module>
    from parampool.menu.DataItem import DataItem
ImportError: No module named menu.DataItem
###### 

So here some modules are missing?

I am not able to run the rest at all (Django1,2 and flask2)
Example for django2:
###### 

tito@terminator:~/web_plot/parampool-master/parampool/tests$ python generate_django2.py 
sh: 1: django-admin.py: not found
Traceback (most recent call last):
  File "generate_django2.py", line 3, in <module>
    generate(myfunc)
  File "/usr/local/lib/python2.7/dist-packages/parampool/generator/django/generator.py", line 71, in generate
    start_all(projectname, appname, project_dir, enable_login)
  File "/usr/local/lib/python2.7/dist-packages/parampool/generator/django/django_setup.py", line 204, in start_all
    os.chdir(projectname)
OSError: [Errno 2] No such file or directory: 'myfunc'
###### 

but myfunc is defined in compute.py

Please give me more detailed step by step instructions, I guess I am doing something wrong.

All the best,
Trifon

**Comment by hplgit** [comment]
Seems that you have not installed what you need. Which packages have you installed and how? Here is a list: http://hplgit.github.io/parampool/doc/pub/._pp006.html#___sec44

The first error says that it cannot find parampool. The next example definitely calls up an installed parampool, but there it seems that you have not installed django since django-admin.py is not available.

The tests in the tests directory are for automatic unit testing. I advise you to go to the examples in the parampool tutorial, doc/src/pp/src-pp, and run them in the order they appear in the tutorial. These examples are meaningful - the tests in tests are more for pure testing.

**Comment by Trifonoff** [comment]
Dear Hans,

Thank you for your help, however i still have problems.

I installed all needed listed in  http://hplgit.github.io/parampool/doc/pub/._pp006.html#___sec44
- I had to install "odespy" too.
  For parampool, I first downloaded the .zip file from your git and extract in my home directory and
  then when I am in the parampool-master directory I am running:

###################
tito@terminator:~/parampool-master$ sudo python setup.py install
[sudo] password for tito: 
running install
running build
running build_py
running install_lib
copying build/lib.linux-x86_64-2.7/parampool/generator/flask/static.tar.gz -> /usr/local/lib/python2.7/dist-packages/parampool/generator/flask
copying build/lib.linux-x86_64-2.7/parampool/generator/django/static.tar.gz -> /usr/local/lib/python2.7/dist-packages/parampool/generator/django
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/parampool-0.1.egg-info
Writing /usr/local/lib/python2.7/dist-packages/parampool-0.1.egg-info
###################

All seams to be ok:

Nevertheless, if I follow you suggestion and try to run one of the examples i have another missing 
library:

tito@terminator:~/parampool-master/doc/src/pp/src-pp/flask4$ python generate.py Traceback (most recent call last):
  File "generate.py", line 4, in <module>
    generate(compute_motion_and_forces, MathJax=True)
  File "/usr/local/lib/python2.7/dist-packages/parampool/generator/flask/generator.py", line 99, in generate
    doc, login=enable_login, latex_name=latex_name)
  File "/usr/local/lib/python2.7/dist-packages/parampool/generator/flask/generate_template.py", line 479, in generate_template
    doc = run_doconce_on_text(compute_function.**doc**)
  File "/usr/local/lib/python2.7/dist-packages/parampool/generator/flask/generate_template.py", line 439, in run_doconce_on_text
    from doconce.common import fix_backslashes
ImportError: No module named doconce.common

Any ideas?

Thanks,
Trifon

**Comment by hplgit** [comment]
Here you try to run flask4, which is a quite advanced app using the doconce tool, which you have not installed. Try some simpler tutorial demos first. Start with flask1...

Thanks for pointing out the dependence of tutorial examples on odespy!

**Comment by Trifonoff** [comment]
Hi I should have mentioned that I naturally started with flask1.
I see an error output (it was given in my first post):

For flask1:

#############################
tito@terminator:~/web_plot/parampool-master/parampool/src/pp/src-pp/flask1$ python generate.py 

**\* Warning:
compute_drag_free_landing has positional arguments.
We recommend to use keyword arguments only since this
generator can then detect the type of each argument and
assign the proper form field type.

The default form field for the positional arguments is
FloatField, which requires explicit conversion
for all arguments that are not of this type.
See controller.py, # Convert data ... for what type
of code that may be needed.

Flask main application written to controller.py.
Usage: python controller.py
#############################

and then:
############################
tito@terminator:~/web_plot/parampool-master/parampool/src/pp/src-pp/flask1$ python controller.py 
Traceback (most recent call last):
  File "controller.py", line 5, in <module>
    from model import DragFreeLanding
  File "/home/tito/web_plot/parampool-master/parampool/src/pp/src-pp/flask1/model.py", line 2, in <module>
    from parampool.html5.flask.fields import HTML5FloatField
  File "/usr/local/lib/python2.7/dist-packages/parampool/html5/flask/fields.py", line 10, in <module>
    from parampool.menu.DataItem import DataItem
ImportError: No module named menu.DataItem

I am not sure I can find  parampool.menu.DataItem in the whole parampool-master directory.

I can find  parampool.pool.DataItem, but I guess that is something else.

Trifon

**Comment by hplgit** [comment]
OK, I understand! At some point "menu" was replaced by "pool", but seemingly not everywhere in the code. My installation had an old menu directory so things worked.

Do a git clone on parampool (do not use the zip file), run setup.py and try again. The parampool.pool.DataItem is the right construction. Anything with "menu" is wrong.

**Comment by Trifonoff** [comment]
Yes... now it seems to work just fine! Thanks for sharing! It will take me some time, but I will post my web page when is ready.

Trifon

**Comment by hplgit** [comment]
Great! Please report any problems or unclear points in the documentation.
